### ISSUE TITLE
Please add starter files to repo

### ISSUE THREAD

**Issue by filmaj** [adobe/oclif-base-index-command#1]
What is required: a license (MIT or Apache 2 recommended), appropriate license headers, contributing.md that requires contributors sign a CLA. These are requirements from our friends from Adobe legal.

Recommended: code of conduct, issue + pull request templates, readme.

Grab whatever you need from github.com/adobe/starter-repo.

**Comment by purplecabbage** [comment]
https://github.com/adobe/aio-cli-plugin-boilerplate is there just for this purpose.

**Comment by shazron** [comment]
@purplecabbage didn't know about that. maybe we should make a command to generate our plugin. In any case, this repo is not really a plugin, since it just exports a class.

**Comment by purplecabbage** [comment]
that was my stretch goal, I ran out of time.
.. and good point on the 'not a plugin ...'
